const initialState = {
  auth: {
    loading: false,
    isAuthenticated: false,
    email: null,
    access_token: null,
    first_name: null,
    last_name: null,
    role: null,
    position: null,
    authority: [],
    chief_division: null,
    language: "",
  },
  admins: {
    loading: false,
    data: [],
    labels: [],
    statuses: [],
    filter: {},
  },
  sales: {
    loading: false,
    data: [],
    assignments: [],
    positions: [],
    unassign: [],
    filter: {},
  },
  sales_types: {
    loading: false,
    data: [],
    meta: [],
  },
  attendance_history: {
    loading: false,
    data: [],
    meta: [],
    filter: {},
  },
  attendance_category: {
    loading: false,
    data: [],
    meta: [],
    filter: {},
  },
  regions: {
    loading: false,
    data: [],
    meta: [],
    filter: {},
  },
  branches: {
    loading: false,
    data: [],
    meta: [],
    filter: {},
  },
  sub_category: {
    loading: false,
    data: [],
    meta: [],
    filter: {},
  },
  areas: {
    loading: false,
    data: [],
    meta: [],
    filter: {},
  },
  subareas: {
    loading: false,
    data: [],
    meta: [],
    filter: {},
  },
  countries: {
    loading: false,
    data: [],
    filter: {},
  },
  provinces: {
    loading: false,
    data: [],
    filter: {},
  },
  cities: {
    loading: false,
    data: [],
    filter: {},
  },
  districts: {
    loading: false,
    data: [],
    filter: {},
  },
  villages: {
    loading: false,
    data: [],
    filter: {},
  },
  company_codes: {
    loading: false,
    data: [],
    filter: {},
  },
  category_list: {
    loading: false,
    data: [],
    filter: {},
  },
  todo_list: {
    loading: false,
    response_code: {},
    message: {},
    data: [],
    meta: [],
  },
  genders: {
    loading: false,
    data: [],
    filter: {},
  },
  roles: {
    loading: false,
    data: [],
    filter: {},
  },
  targets: {
    loading: false,
    data: [],
    filter_country: {},
    filter_province: {},
    filter_city: {},
    filter_district: {},
    loading_country: true,
    loading_province: true,
    loading_city: true,
    loading_district: true,
    statistic: [],
  },
  manage_target_types: {
    loading: false,
    data: [],
    filter: {},
  },
  manage_targets: {
    loading: false,
    data: [],
    region_data: [],
    monthly_data: [],
    filter: {},
  },
  companies: {
    loading: false,
    data: [],
    filter: {},
  },
  todos: {
    loading: false,
    data: [],
    filter: {},
  },
  reviews: {
    loading: false,
    data: [],
    meta: [],
    filter: {},
  },
  reports: {
    loading: false,
    charts: [],
    sales: [],
    filter: {},
  },
  ottopay: {
    loading: false,
    data: [],
    filter: {},
  },
  requests: {
    loading: false,
    data: [],
    modules: [],
    status: [],
    action_types: [],
    filter: {},
  },
  notifications: {
    loading: false,
    data: [],
    meta: [],
  },
  ottocash_user: {
    loading: false,
    data: [],
    meta: [],
    filter: {},
  },
  clusters: {
    loading: false,
    data: [],
    meta: [],
  },
  calendars: {
    loading: false,
    data: [],
    meta: [],
  },
  merchants: {
    loading: false,
    data: [],
    meta: [],
  },
  call_plan: {
    loading: false,
    data: [],
    meta: [],
    filter: {},
  },
  call_plan_merchants: {
    loading: false,
    data: [],
    meta: [],
    filter: {},
  },
  recruitments: {
    loading: false,
    data: [],
    meta: [],
    filter: {},
  },
  sales_levels: {
    loading: false,
    data: [],
    meta: [],
    filter: {},
  },
  sales_level_assignments: {
    loading: false,
    data: [],
    meta: [],
    filter: {},
  },
  acquisitions: {
    loading: false,
    data: [],
    one: {},
    filter: {},
    meta: [],
  },
  merchant_types: {
    loading: false,
    data: [],
    one: {},
    filter: {},
    meta: [],
  },
  activities: {
    loading: false,
    data: [],
    one: {},
    filter: {},
    meta: [],
  },
  task_category: {
    loading: false,
    data: [],
    one: {},
    filter: {},
    meta: [],
  },
  salesmen_location: {
    loading: false,
    data: [],
    one: {},
    filter: {},
    meta: [],
  },
  task_management: {
    loading: false,
    data: [],
    one: {},
    filter: {},
    meta: [],
  },
  minio: {
    loading: false,
    data: [],
    one: {},
    filter: {},
    meta: [],
  },
};

export default initialState;
