export const NEWAPI = process.env.REACT_APP_API_URL_GO;
export const NEWAPI_V2 = process.env.REACT_APP_API_URL_GO_V2;
export const NEWAPI_CALL_PLAN = process.env.REACT_APP_API_URL_GO_CALL_PLAN;
export const NEWAPI_CALL_PLAN_v2 =
  process.env.REACT_APP_API_URL_GO_CALL_PLAN_v2;
export const NEWAPI_CALL_PLAN_v23 =
  process.env.REACT_APP_API_URL_GO_CALL_PLAN_v2_3;
export const NEWAPI_V2_1 = process.env.REACT_APP_API_URL_GO_V2_1;
export const NEWAPI_V2_2 = process.env.REACT_APP_API_URL_GO_V2_2;
export const NEWAPI_V2_2_1 = process.env.REACT_APP_API_URL_GO_V2_2_1;
export const NEWAPI_V2_3 = process.env.REACT_APP_API_URL_GO_V2_3;

export const NEWAPI_FEEDING_LONGLAT =
  process.env.REACT_APP_API_URL_GO_FEEDING_LONGLAT;
export const REACT_APP_API_KEY_GOOGLE_MAP =
  process.env.REACT_APP_API_KEY_GOOGLE_MAP;
export const REACT_APP_DEFAULT_LATITUDE =
  process.env.REACT_APP_DEFAULT_LATITUDE;
export const REACT_APP_DEFAULT_LONGITUDE =
  process.env.REACT_APP_DEFAULT_LONGITUDE;
export const NOTIFICATION_API = process.env.REACT_APP_API_URL_NOTIFICATION;

export const FETCHING = "FETCHING";
export const FETCHING_ADMIN = "FETCHING_ADMIN";
export const FETCHING_CITY = "FETCHING_CITY";
export const FETCHING_COMPANY_CODE = "FETCHING_COMPANY_CODE";
export const FETCHING_COUNTRY = "FETCHING_COUNTRY";
export const FETCHING_DISTRICT = "FETCHING_DISTRICT";
export const FETCHING_GENDER = "FETCHING_GENDER";
export const FETCHING_PROVINCE = "FETCHING_PROVINCE";
export const FETCHING_ROLE = "FETCHING_ROLE";
export const FETCHING_SALE = "FETCHING_SALE";
export const FETCHING_TARGET = "FETCHING_TARGET";
export const FETCHING_VILLAGE = "FETCHING_VILLAGE";
export const FETCHING_TODO = "FETCHING_TODO";
export const FETCHING_REVIEW = "FETCHING_REVIEW";
export const FETCHING_CATEGORY_LIST = "FETCHING_CATEGORY_LIST";
export const FETCHING_SUB_CATEGORY_LIST = "FETCHING_SUB_CATEGORY_LIST";
export const FETCHING_TODO_LIST = "FETCHING_TODO_LIST";
export const FETCHING_TODO_DETAIL = "FETCHING_TODO_DETAIL";
export const FETCHING_ATTENDANCE_HISTORY = "FETCHING_ATTENDANCE_HISTORY";
export const FETCHING_ATTENDANCE_CATEGORY = "FETCHING_ATTENDANCE_CATEGORY";

export const ERROR_FETCHING = "ERROR_FETCHING";
export const ERROR_FETCHING_ADMIN = "ERROR_FETCHING_ADMIN";
export const ERROR_FETCHING_CITY = "ERROR_FETCHING_CITY";
export const ERROR_FETCHING_COMPANY_CODE = "ERROR_FETCHING_COMPANY_CODE";
export const ERROR_FETCHING_COUNTRY = "ERROR_FETCHING_COUNTRY";
export const ERROR_FETCHING_DISTRICT = "ERROR_FETCHING_DISTRICT";
export const ERROR_FETCHING_GENDER = "ERROR_FETCHING_GENDER";
export const ERROR_FETCHING_PROVINCE = "ERROR_FETCHING_PROVINCE";
export const ERROR_FETCHING_ROLE = "ERROR_FETCHING_ROLE";
export const ERROR_FETCHING_SALE = "ERROR_FETCHING_SALE";
export const ERROR_FETCHING_TARGET = "ERROR_FETCHING_TARGET";
export const ERROR_FETCHING_VILLAGE = "ERROR_FETCHING_VILLAGE";
export const ERROR_FETCHING_TODO = "ERROR_FETCHING_TODO";
export const ERROR_FETCHING_REVIEW = "ERROR_FETCHING_REVIEW";
export const ERROR_FETCHING_CATEGORY_LIST = "ERROR_FETCHING_CATEGORY_LIST";
export const ERROR_FETCHING_SUB_CATEGORY_LIST =
  "ERROR_FETCHING_SUB_CATEGORY_LIST";
export const ERROR_FETCHING_TODO_LIST = "ERROR_FETCHING_TODO_LIST";
export const ERROR_FETCHING_TODO_DETAIL = "ERROR_FETCHING_TODO_DETAIL";
export const ERROR_FETCHING_ATTENDANCE_HISTORY =
  "ERROR_FETCHING_ATTENDANCE_HISTORY";
export const ERROR_FETCHING_ATTENDANCE_CATEGORY =
  "ERROR_FETCHING_ATTENDANCE_CATEGORY";

export const GET_ADMINS = "GET_ADMINS";
export const GET_ADMIN_STATUS = "GET_ADMIN_STATUS";
export const GET_ADMIN = "GET_ADMIN";
export const GET_SALES = "GET_SALES";
export const GET_ASSIGNMENT_SALES = "GET_ASSIGNMENT_SALES";
export const GET_POSITIONS_SALES = "GET_POSITIONS_SALES";
export const GET_UNASSIGN_SALES = "GET_UNASSIGN_SALES";
export const GET_SALE = "GET_SALE";
export const GET_TODOS = "GET_TODOS";
export const GET_TODO = "GET_TODO";
export const GET_REVIEWS = "GET_REVIEWS";
export const GET_REVIEW = "GET_REVIEW";
export const GET_TODO_LIST = "GET_TODO_LIST";
export const GET_TODO_DETAIL = "GET_TODO_DETAIL";
export const GET_ATTENDANCE_HISTORY = "GET_ATTENDANCE_HISTORY";
export const GET_ATTENDANCE_CATEGORY = "GET_ATTENDANCE_CATEGORY";

export const GET_COUNTRIES = "GET_COUNTRIES";
export const GET_PROVINCES = "GET_PROVINCES";
export const GET_CITIES = "GET_CITIES";
export const GET_DISTRICTS = "GET_DISTRICTS";
export const GET_VILLAGES = "GET_VILLAGES";
export const FILTER_COUNTRY = "FILTER_COUNTRY";
export const FILTER_PROVINCE = "FILTER_PROVINCE";
export const FILTER_CITY = "FILTER_CITY";
export const FILTER_DISTRICT = "FILTER_DISTRICT";
export const FILTER_VILLAGE = "FILTER_VILLAGE";
export const FILTER_TODOS = "FILTER_TODOS";
export const FETCHING_TARGET_COUNTRY = "FETCHING_TARGET_COUNTRY";
export const FETCHING_TARGET_PROVINCE = "FETCHING_TARGET_PROVINCE";
export const FETCHING_TARGET_CITY = "FETCHING_TARGET_CITY";
export const FETCHING_TARGET_DISTRICT = "FETCHING_TARGET_DISTRICT";

export const GET_COMPANY_CODES = "GET_COMPANY_CODES";
export const GET_GENDERS = "GET_GENDERS";
export const GET_ROLES = "GET_ROLES";
export const GET_ROLE = "GET_ROLE";
export const GET_TARGET_STATISTIC = "GET_TARGET_STATISTIC";
export const GET_CATEGORY_LIST = "GET_CATEGORY_LIST";
export const GET_SUB_CATEGORY = "GET_SUB_CATEGORY";

export const AUTH_REQUEST = "AUTH_REQUEST";
export const AUTH_RECEIVED = "AUTH_RECEIVED";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_SIGNOUT = "AUTH_SIGNOUT";

export const FETCHING_MANAGE_TARGET = "FETCHING_MANAGE_TARGET";
export const ERROR_FETCHING_MANAGE_TARGET = "ERROR_FETCHING_MANAGE_TARGET";
export const GET_MANAGE_TARGETS = "GET_MANAGE_TARGETS";
export const GET_MANAGE_TARGETS_REGIONAL = "GET_MANAGE_TARGETS_REGIONAL";
export const GET_MANAGE_TARGETS_MONTHLY = "GET_MANAGE_TARGETS_MONTHLY";
export const GET_MANAGE_TARGET = "GET_MANAGE_TARGET";

export const FETCHING_COMPANY = "FETCHING_COMPANY";
export const ERROR_FETCHING_COMPANY = "ERROR_FETCHING_COMPANY";
export const GET_COMPANIES = "GET_COMPANIES";
export const GET_COMPANY = "GET_COMPANY";

export const FETCHING_MANAGE_TARGET_TYPE = "FETCHING_MANAGE_TARGET_TYPE";
export const ERROR_FETCHING_MANAGE_TARGET_TYPE =
  "ERROR_FETCHING_MANAGE_TARGET_TYPE";
export const GET_MANAGE_TARGET_TYPES = "GET_MANAGE_TARGET_TYPES";
export const GET_MANAGE_TARGET_TYPE = "GET_MANAGE_TARGET_TYPE";

export const FETCHING_REQUEST = "FETCHING_REQUEST";
export const ERROR_FETCHING_REQUEST = "ERROR_FETCHING_REQUEST";
export const GET_REQUESTS = "GET_REQUESTS";
export const GET_REQUEST = "GET_REQUEST";
export const GET_REQUEST_ACTION_TYPE = "GET_REQUEST_ACTION_TYPE";
export const GET_REQUEST_STATUS = "GET_REQUEST_STATUS";
export const GET_REQUEST_MODULE = "GET_REQUEST_MODULE";

export const FETCHING_REGION = "FETCHING_REGION";
export const ERROR_FETCHING_REGION = "ERROR_FETCHING_REGION";
export const GET_REGIONS = "GET_REGIONS";
export const GET_REGION = "GET_REGION";
export const GET_REGIONS_PROVINCES = "GET_REGIONS_PROVINCES";

export const FETCHING_ASSIGNMENT_ROLE = "FETCHING_ASSIGNMENT_ROLE";
export const ERROR_FETCHING_ASSIGNMENT_ROLE = "ERROR_FETCHING_ASSIGNMENT_ROLE";
export const GET_ASSIGNMENT_ROLES = "GET_ASSIGNMENT_ROLES";
export const GET_ASSIGNMENT_ROLE = "GET_ASSIGNMENT_ROLE";

export const FETCHING_REPORT = "FETCHING_REPORT";
export const ERROR_FETCHING_REPORT = "ERROR_FETCHING_REPORT";
export const GET_SALES_REPORTS = "GET_SALES_REPORTS";
export const GET_REPORTS = "GET_REPORTS";
export const GET_REPORT = "GET_REPORT";

export const FETCHING_BRANCH = "FETCHING_BRANCH";
export const ERROR_FETCHING_BRANCH = "ERROR_FETCHING_BRANCH";
export const GET_BRANCHES = "GET_BRANCHES";
export const GET_BRANCH = "GET_BRANCH";

export const FETCHING_AREA = "FETCHING_AREA";
export const ERROR_FETCHING_AREA = "ERROR_FETCHING_AREA";
export const GET_AREAS = "GET_AREAS";
export const GET_AREA = "GET_AREA";

export const FETCHING_SUBAREA = "FETCHING_SUBAREA";
export const ERROR_FETCHING_SUBAREA = "ERROR_FETCHING_SUBAREA";
export const GET_SUBAREAS = "GET_SUBAREAS";
export const GET_SUBAREA = "GET_SUBAREA";

export const FETCHING_OTTOPAY = "FETCHING_OTTOPAY";
export const ERROR_FETCHING_OTTOPAY = "ERROR_FETCHING_OTTOPAY";
export const GET_OTTOPAYS = "GET_OTTOPAYS";
export const GET_OTTOPAY = "GET_OTTOPAY";

export const FETCHING_OTTOCASH = "FETCHING_OTTOCASH";
export const ERROR_FETCHING_OTTOCASH = "ERROR_FETCHING_OTTOCASH";
export const GET_OTTOCASHS = "GET_OTTOCASHS";
export const GET_OTTOCASH = "GET_OTTOCASH";

export const FETCHING_NOTIFICATIONS = "FETCHING_NOTIFICATIONS";
export const ERROR_FETCHING_NOTIFICATIONS = "ERROR_FETCHING_NOTIFICATIONS";
export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";

export const FETCHING_CLUSTER = "FETCHING_CLUSTER";
export const ERROR_FETCHING_CLUSTER = "ERROR_FETCHING_CLUSTER";
export const GET_CLUSTERS = "GET_CLUSTERS";
export const GET_CLUSTER = "GET_CLUSTER";

export const FETCHING_CALENDAR = "FETCHING_CALENDAR";
export const ERROR_FETCHING_CALENDAR = "ERROR_FETCHING_CALENDAR";
export const GET_CALENDARS = "GET_CALENDARS";
export const GET_CALENDAR = "GET_CALENDAR";

export const FETCHING_MERCHANT = "FETCHING_MERCHANT";
export const ERROR_FETCHING_MERCHANT = "ERROR_FETCHING_MERCHANT";
export const GET_MERCHANTS = "GET_MERCHANTS";
export const GET_MERCHANT = "GET_MERCHANT";

export const FETCHING_CALL_PLAN = "FETCHING_CALL_PLAN";
export const ERROR_FETCHING_CALL_PLAN = "ERROR_FETCHING_CALL_PLAN";
export const GET_CALL_PLANS = "GET_CALL_PLANS";
export const GET_CALL_PLAN = "GET_CALL_PLAN";

export const FETCHING_CALL_PLAN_MERCHANTS = "FETCHING_CALL_PLAN_MERCHANTS";
export const ERROR_FETCHING_CALL_PLAN_MERCHANTS =
  "ERROR_FETCHING_CALL_PLAN_MERCHANTS";
export const GET_CALL_PLAN_MERCHANTS = "GET_CALL_PLAN_MERCHANTS";

export const FETCHING_SALES_TYPE = "FETCHING_SALES_TYPE";
export const ERROR_FETCHING_SALES_TYPE = "ERROR_FETCHING_SALES_TYPE";
export const GET_SALES_TYPE = "GET_SALES_TYPE";

export const FETCHING_RECRUITMENTS = "FETCHING_RECRUITMENTS";
export const ERROR_FETCHING_RECRUITMENT = "ERROR_FETCHING_RECRUITMENT";
export const GET_RECRUITMENTS = "GET_RECRUITMENTS";
export const GET_RECRUITMENT = "GET_RECRUITMENT";

export const FETCHING_SALES_LEVEL = "FETCHING_SALES_LEVEL";
export const ERROR_FETCHING_SALES_LEVEL = "ERROR_FETCHING_SALES_LEVEL";
export const GET_SALES_LEVELS = "GET_SALES_LEVELS";
export const GET_SALES_LEVEL = "GET_SALES_LEVEL";

export const FETCHING_SALES_LEVEL_ASSIGNMENT =
  "FETCHING_SALES_LEVEL_ASSIGNMENT";
export const ERROR_FETCHING_SALES_LEVEL_ASSIGNMENT =
  "ERROR_FETCHING_SALES_LEVEL_ASSIGNMENT";
export const GET_SALES_LEVEL_ASSIGNMENTS = "GET_SALES_LEVEL_ASSIGNMENTS";
export const GET_SALES_LEVEL_ASSIGNMENT = "GET_SALES_LEVEL_ASSIGNMENT";

export const FETCHING_ACQUISITION = "FETCHING_ACQUISITION";
export const ERROR_FETCHING_ACQUISITION = "ERROR_FETCHING_ACQUISITION";
export const GET_ACQUISITION = "GET_ACQUISITION";
export const GET_ACQUISITIONS = "GET_ACQUISITIONS";

export const FETCHING_MERCHANT_TYPE = "FETCHING_MERCHANT_TYPE";
export const GET_MERCHANT_TYPES = "GET_MERCHANT_TYPES";
export const GET_MERCHANT_TYPE = "GET_MERCHANT_TYPE";
export const ERROR_FETCHING_MERCHANT_TYPE = "ERROR_FETCHING_MERCHANT_TYPE";

export const FETCHING_SALES_ACTIVITIES = "FETCHING_SALES_ACTIVITIES";
export const GET_SALES_ACTIVITIES = "GET_SALES_ACTIVITIES";
export const GET_SALES_ACTIVITY = "GET_SALES_ACTIVITY";
export const ERROR_FETCHING_SALES_ACTIVITIES =
  "ERROR_FETCHING_SALES_ACTIVITIES";

export const FETCHING_TASK_CATEGORY = "FETCHING_TASK_CATEGORY";
export const ERROR_FETCHING_TASK_CATEGORY = "ERROR_FETCHING_TASK_CATEGORY";
export const GET_CATEGORY = "GET_CATEGORY";
export const GET_CATEGORIES = "GET_CATEGORIES";

export const FETCHING_SALESMEN_LOCATION = "FETCHING_SALESMEN_LOCATION";
export const ERROR_FETCHING_SALESMEN_LOCATION =
  "ERROR_FETCHING_SALESMEN_LOCATION";
export const GET_SALESMAN_LOCATION = "GET_SALESMAN_LOCATION";
export const GET_SALESMEN_LOCATION = "GET_SALESMEN_LOCATION";

export const FETCHING_TASK_MANAGEMENT = "FETCHING_TASK_MANAGEMENT";
export const ERROR_FETCHING_TASK_MANAGEMENT = "ERROR_FETCHING_TASK_MANAGEMENT";
export const GET_TASK_MANAGEMENT = "GET_TASK_MANAGEMENT";
export const GET_TASK_MANAGEMENTS = "GET_TASK_MANAGEMENT";

export const FETCHING_MINIO = "FETCHING_MINIO";
export const ERROR_FETCHING_MINIO = "ERROR_FETCHING_MINIO";
export const GET_MINIO = "GET_MINIO";
